const textos = [
    "Era el mejor de los tiempos, era el peor de los tiempos, la edad de la sabiduría, y también de la locura; la época de las creencias y de la incredulidad; la era de la luz y de las tinieblas; la primavera de la esperanza y el invierno de la desesperación. Todo lo poseíamos, pero no teníamos nada; caminábamos en derechura al cielo y nos extraviábamos por el camino opuesto. En una palabra, aquella época era tan parecida a la actual, que nuestras más notables autoridades insisten en que, tanto en lo que se refiere al bien como al mal, sólo es aceptable la comparación en grado superlativo.",
    "Aun lado y a otro del helado cauce de erguía un oscuro bosque de abetos de ceñudo aspecto. Hacía poco que el viento había despojado a los árboles de la capa de hielo que los cubría y, en medio de la escasa claridad, que se iba debilitando por momentos, parecían inclinarse unos hacia otros, negros y siniestros. Reinaba un profundo silencio en toda la vasta extensión de aquella tierra. Era la desolación misma, sin vida, sin movimiento, tan solitaria y fría que ni siquiera bastaría decir, para describirla, que su esencia era la tristeza.",
    "Si vas a leer esto, no te preocupes. Al cabo de un par de páginas ya no querrás estar aquí. Así que olvídalo. Aléjate. Lárgate mientras sigas entero. Sálvate. Seguro que hay algo mejor en la televisión. O, ya que tienes tanto tiempo libre, a lo mejor puedes hacer un cursillo nocturno. Hazte médico. Puedes hacer algo útil con tu vida. Llévate a ti mismo a cenar. Tíñete el pelo. No te vas a volver más joven. Al principio lo que se cuenta aquí te va a cabrear. Luego se volverá cada vez peor.",
    "La candente mañana de febrero en que Beatriz Viterbo murió, después de una imperiosa agonía que no se rebajó un solo instante ni al sentimentalismo ni al miedo, noté que las carteleras de fierro de la Plaza Constitución habían renovado no sé qué aviso de cigarrillos rubios; el hecho me dolió, pues comprendí que el incesante y vasto universo ya se apartaba de ella y que ese cambio era el primero de una serie infinita.",
    "El Viajero a través del Tiempo (pues convendrá llamarle así al hablar de él) nos exponía una misteriosa cuestión. Sus ojos grises brillaban lanzando centellas, y su rostro, habitualmente pálido, mostrábase encendido y animado. El fuego ardía fulgurante y el suave resplandor de las lámparas incandescentes, en forma de lirios de plata, se prendía en las burbujas que destellaban y subían dentro de nuestras copas.",
    "Aquellas alucinantes sesiones quedaron de tal modo impresas en la memoria de los niños, que muchos años más tarde, un segundo antes de que el oficial de los ejércitos regulares diera la orden de fuego al pelotón de fusilamiento, el coronel Aureliano Buendía volvió a vivir la tibia tarde de marzo en que su padre interrumpió la lección de física, y se quedó fascinado con la mano en el aire y los ojos inmóviles, oyendo a la distancia los pífanos y tambores y sonajas de los gitanos que una vez más llegaban a la aldea, pregonando el último y asombroso descubrimiento de los sabios de Memphis.",
    "Yo, Tiberio Claudio Druso Nérón Germánico Esto-y-lo-otro-y-lo-de-más-allá (porque no pienso molestarlos todavía con todos mis títulos), que otrora, no hace mucho, fui conocido por mis parientes, amigos y colaboradores como Claudio el Idiota, o Ese Claudio, o Claudio el Tartamudo o Clau-Clau-Claudio, o, cuando mucho, como El pobre tío Claudio, voy a escribir ahora esta extraña historia de mi vida.",
    "Constituía un placer especial ver las cosas consumidas, ver los objetos ennegrecidos y cambiados. Con la punta de bronce del soplete en sus puños, con aquella gigantesca serpiente escupiendo su petróleo venenoso sobre el mundo, la sangre le latía en la cabeza y sus manos eran las de un fantástico director tocando todas las sinfonías del fuego y de las llamas para destruir los guiñapos y ruinas de la Historia.",
    "Estás a punto de empezar a leer la nueva novela de Italo Calvino, Si una noche de invierno un viajero. Relájate. Recógete. Aleja de ti cualquier otra idea. Deja que el mundo que te rodea se esfume en lo indistinto. La puerta es mejor cerrarla; al otro lado siempre está la televisión encendida. Dilo en seguida, a los demás: «¡No, no quiero ver la televisión!» Alza la voz, si no te oyen: «¡Estoy leyendo! ¡No quiero que me molesten!» Quizá no te han oído, con todo ese estruendo; dilo más fuerte, grita: «¡Estoy empezando a leer la nueva novela de Italo Calvino!» O no lo digas si no quieres; esperemos que te dejen en paz.",
    "Lolita, luz de mi vida, fuego de mis entrañas. Pecado mío, alma mía. Lo-li-ta: la punta de la lengua emprende un viaje de tres pasos desde el borde del paladar para apoyarse, en el tercero, en el borde de los dientes. Lo. Li. Ta. Era Lo, sencillamente Lo, por la mañana, un metro cuarenta y ocho de estatura con pies descalzos. Era Lola con pantalones. Era Dolly en la escuela. Era Dolores cuando firmaba. Pero en mis brazos era siempre Lolita.",
    "Hora crepuscular. Un guardillón con ventano angosto, lleno de sol. Retratos, grabados, autógrafos repartidos por las paredes, sujetos con chinches de dibujante. Conversación lánguida de un hombre ciego y una mujer pelirrubia, triste y fatigada. El hombre ciego es un hiperbólico andaluz, poeta de odas y madrigales, Máximo Estrella. A la pelirrubia, por ser francesa, le dicen en la vecindad Madama Collet.",
    "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor. Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lentejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda. El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los días de entre semana se honraba con su vellori de lo más fino. Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera. Frisaba la edad de nuestro hidalgo con los cincuenta años, era de complexión recia, seco de carnes, enjuto de rostro; gran madrugador y amigo de la caza. Quieren decir que tenía el sobrenombre de Quijada o Quesada (que en esto hay alguna diferencia en los autores que deste caso escriben), aunque por conjeturas verosímiles se deja entender que se llama Quijana; pero esto importa poco a nuestro cuento; basta que en la narración dél no se salga un punto de la verdad.",
    "Soy un hombre invisible. No, no soy uno de aquellos trasgos que atormentaban a Edgar Allan Poe, ni tampoco uno de esos ectoplasmas de las películas de Hollywood. Soy un hombre real, de carne y hueso, con músculos y humores, e incluso cabe afirmar que poseo una mente. Sabed que si soy invisible ello se debe, tan sólo, a que la gente se niega a verme. Soy como las cabezas separadas del tronco que a veces veis en las barracas de feria, soy como un reflejo de crueles espejos con duros cristales deformantes. Cuantos se acercan a mí únicamente ven lo que me rodea, o inventos de su imaginación. Lo ven todo, cualquier cosa, menos mi persona.",
    "Soy un hombre enfermo... Un hombre malo. No soy agradable. Creo que padezco del hígado. De todos modos, nada entiendo de mi enfermedad y no sé con certeza lo que me duele. No me cuido y jamás me he cuidado, aunque siento respeto por la medicina y los médicos. Además, soy extremadamente supersticioso, cuando menos lo bastante para respetar la medicina (tengo suficiente cultura para no ser supersticioso, pero lo soy). Sí, no quiero curarme por rabia. Esto, seguramente, ustedes no lo pueden entender. Pero yo sí lo entiendo."
];